### PR TITLE
#(flow: formatRoute):  Adding & updating flow types

### PR DESCRIPTION
**Pull request by zackljackson**
Updated gitignore, added and amended flow-types

@faceyspacey Lemme know if this is on track

### CODE REVIEW

**Comment by zackljackson** [comment]
Also, in formatRoute.js Is scene still going to be attached to the Route type?

```
  route.scene = typeToScene(type)
  // set default path for NOT_FOUND actions if necessary
  if (!route.path && isNotFound(type)) {
    route.path = route.scene
      ? `/${r.scene.toLowerCase()}/not-found`
      : '/not-found'
  }

  return route
}

**Comment by faceyspacey** [comment]
the scene will be attached to routes if you're using `createScene`.  So unless we attach a default scene like `route.scene = 'default'`, it's an optional key on the object. Let's just consider that, and if somehow that makes typing easier we can add it in `formatRoutes` if no sense is supplied (i.e. if the routes wasn't run through `createScene` initially).

The idea is you can optionally generate your actions, action creators, etc, by running your routes through `createScene(routes, { scene: 'foo' })`, and then you can pass those routes to `createRouter({ ...fooSceneRoutes, ...barSceneRoutes })`.

So using `createScene` isn't mandatory. 

Another quick thing: change `RoutesMap` to be just `Routes`. You'll notice `routesMap` is now just `routes` throughout the codebase. So the types should reflect the same.

As far as `RoutesInput` goes--obviously the idea is we accept a different type for input, and transform it by adding/changing keys until it fits the precise `Routes` and `Route` type used internally.

**Comment by zackljackson** [comment]
@faceyspacey Okay I did a find replace on RoutesMap => Routes

I am using, because we are accessing an object, correct?
Anyways for the scenarios I have encountered thus far, this made more sense. 


```
export type Routes = {
  [key: string]: Route
}

**Comment by zackljackson** [comment]
@faceyspacey  Theres another PR behind this one as well, Just let me know if the context if change here is good. Then I can always open another PR.

Small changes but it adds up to lots of stuff to look at.

**Comment by faceyspacey** [comment]
> I am using, because we are accessing an object, correct?

Not sure what u mean by, both `Routes` and `Route` are objects. And `RouteInput` can both be an object or string.

...as far as the 2 PRs. as soon as im done with something im working on. im gonna commit it to master, and then merge ur original boilerplate-oriented PR.

**Comment by zackljackson** [comment]
Okay, ive updated the other flow types ive added to this PR

**Comment by faceyspacey** [comment]
merged in the other commit

**Pull request closed without merging**
