### PR TITLE
ensures that the querySerializer is used on the initial action so that query params appear during the initial  call

### LINKED ISSUE #265: Initial state does not keep query
Since the project appears to be fragmented, and I'm unsure of the actual state of things, I'm leaving this here. If I can get some guidance as to what branch is current I will make a pr.

I am using the rudy branch currently, it looks like the `initialAction` created inside of the `connectRoutes` function is not being given the querySerializer option, as a result any query params that exist on the initial route are not put into the redux store.

### PR DESCRIPTION
**Pull request by CNDW**
this fixes #265, It took me a little while to find the time to put this in, let me know if I have missed anything.

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
@faceyspacey

**Comment by binocarlos** [comment]
@faceyspacey we just hit the same problem as described in [the original issue](https://github.com/faceyspacey/redux-first-router/issues/265) and pulled this PR into our package.json and it works perfectly - @CNDW thanks! good work sir 👍

**Comment by hedgepigdaniel** [comment]
@ScriptedAlchemy let's merge this fix?

**Comment by ScriptedAlchemy** [comment]
Done

**Comment by baleeds** [comment]
I feel like I'm hitting this issue on `"redux-first-router": "^2.1.1",`.  Is it fixed in that version?

**Pull request merged**
