### PR TITLE
Support passing an additional arg to all thunks

### PR DESCRIPTION
**Pull request by iansinnott**
This PR does exactly what I outlined in this issue: https://github.com/faceyspacey/redux-first-router/issues/54

Some addition things to note:

* Snapshots were updated. I'm not sure why though, because the snapshots differed as soon as I ran the tests, even before I made any changes.
* I took the opportunity to fix a potentially undiscovered bug where thunks depended on a certain global state shap (see c0cb9e7).

### CODE REVIEW

**Comment by iansinnott** [comment]
Not sure what's going on with the tests. Looks like issues with the snapshots but I updated them and everything is passing locally.

**Comment by faceyspacey** [comment]
...i really like this a lot!

...there's one caveat: in the next week or so pre-fetching is finally coming out, and there's a core realization which necessitates a 3rd argument of its own:

we need to pass the action as the third argument. The reason is because `getState` won't reflect the action you want to prefetch as it hasn't happened yet!

So prefetching rests on the premise that you can prefetch based on a potential upcoming action. That ultimately means if you want to take advantage of prefetched thunks, you have to use the type and payload from the 3rd action argument, rather than from `getState().location.type/payload`. You can use other state you might have (while making sure to be cognizant that it will change after the action is actually dispatched), but for prefetching you gotta get the data for the actual fetching from the 3rd action arg.

We could make it an `options` style arg or we could simply put the custom arg always last. 

...And actually I just thought of something crazy that didn't occur to me before:

we can pass modified `getState` that will take the action you want to prefetch actions and it will replace the `type`, `payload` etc in the location state, as if it ran. I gotta think if that will cause any problems. 

If that's the case, your PR will work fine as is. I'm gonna revisit this as I finalize prefetching.

**Comment by iansinnott** [comment]
Gotcha, yeah in that case I'm happy for this PR to just sit here for now. We can revisit once you have prefetching stuffs out the door 👍

**Comment by veddermatic** [comment]
Would love to see the `action` as a third parameter to the thunks, or an additional argument of some kind as this PR implements. I'm bumping into a use case where I want to attach extra data to a thunked route and don't want it in the URL.

**Comment by faceyspacey** [comment]
Hey brother, we got this feature now! ...I really wanted to finish it here in your PR so you could get some recorded credit for it, but with other changes and with the unnecessary extra time it would take it ultimately didn't make sense.

Check it. Now we have a "bag" 3rd arg:

https://gist.github.com/faceyspacey/2771c05a62a338fa6d3d23d76e6e7c5a
All the info is there. Basically there is an `extra` key in that object and the options passed to `connectRoutes` have an `extra` option now.

There's also some notes about that and other features recently added at the top of the repo:
https://github.com/faceyspacey/redux-first-router

Hope all is well. Let me know if I can help in any way.

**Comment by iansinnott** [comment]
Awesome, glad to see the feature made it in either way. I haven't been doing redux stuff much these past few weeks but it looks like my use case is solved 👍

**Pull request closed without merging**
