### PR TITLE
fix(flow types export): fixes export of types by adding flow annotation to index file

### LINKED ISSUE #115: flow types imported from library are all 'any'
Hello

I am trying to import flow types from your library for use in my application. Unfortunately, they appear to be all 'any'. I have this simple example:

```js
/* @flow */
import type { LocationState, NavigationAction } from 'redux-first-router';

const location: LocationState = {
    foo: 'bar',
    car: 1,
};
```

Running `flow` I see `No errors!` and no complaints from my editor (vscode). If I hover over the types, vscode tells me they are 'any'.

I have had a dig around in node_modules/redux-first-router/dist and the `flow-types.js` file is empty. There are type definitions in `flow-types.js.flow` and `index.js.flow`. 

I am have tried v0.0.16-next and v1.9.19 with no success. I am on flow version 0.52.0.

### PR DESCRIPTION
**Pull request by petegleeson**
Fixes #115 by adding the flow annotation to the index file.

I am not sure whether this should be a major version release. Given all the types at the moment are exported as 'any', this change could break consumers using flow.

### CODE REVIEW

**Comment by faceyspacey** [comment]
so this doesn't magically make the types in `src/index.flow.js` work?

**Comment by petegleeson** [comment]
This **does** make the types in `dist/index.js.flow` work

**Comment by faceyspacey** [comment]
so then they are not exported as `any`? Can you clarify what you mean by that?

**Comment by faceyspacey** [comment]
this line:
>Given all the types at the moment are exported as 'any', this change could break consumers using flow.
??

**Comment by petegleeson** [comment]
Before I added `// @flow` to `index.js`, all types imported from this library were 'any'. After this change, these imports will have the correct types. This means that people upgrading to the version with this change could get flow errors.

**Comment by faceyspacey** [comment]
oh, you were talking about the past. It sounded like you were talking about a caveat that applied to the new bright future.

Anyway, thanks for this. We needed this and I haven't had the time to explore it. Glad it worked out so nicely!!

**Comment by petegleeson** [comment]
No worries - finally had some time to do this. So are you going to do a major version release?

**Comment by faceyspacey** [comment]
No. Not many people are using Flow or more would have complained. This is only a fix they'd be looking for. Also, it won't affect runtime behavior. At the end of the day, being that strict isn't practical in this case.

**Comment by faceyspacey** [comment]
Actually, I'll just put it in the `rudy` branch in this case. I'll put publish it in a few hours with some other upgrades. Check the top of the readme for other new things. If you're not using it, there are some breaking changes. They are very quick to fix.

**Comment by petegleeson** [comment]
Ok cool, is the rudy branch stable enough to branch off? Do you have an idea when rudy will be merged into master?

**Comment by faceyspacey** [comment]
We need people to use it to get to that point. Treat it as master.

I didn't get to publish ur fix yet.

**Comment by petegleeson** [comment]
Sure, thanks mate I'll keep an eye on the releases.

**Pull request merged**
